spring:
  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3307/wiredcraft?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&connectTimeout=30000&socketTimeout=30000&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: select 1
      validation-time-out: 300000
      primary:
        jdbc-url: jdbc:mysql://localhost:3307/wiredcraft?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&connectTimeout=30000&socketTimeout=30000&useSSL=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8500 # 配置的开发环境的端口
  devtools:
    restart:
      enabled: true



log:
  path: "/Users/yibo/Documents/wiredcraft/projects/logs"


